
package com.wlopera.cliente.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Sat Oct 27 10:24:12 COT 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "getCMFPorAnnio", namespace = "http://cliente.wlopera.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCMFPorAnnio", namespace = "http://cliente.wlopera.com/")

public class GetCMFPorAnnio {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

