
package com.wlopera.cliente.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Sat Oct 27 10:24:12 COT 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "getListaCMFPorCampeonatoGanadoResponse", namespace = "http://cliente.wlopera.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getListaCMFPorCampeonatoGanadoResponse", namespace = "http://cliente.wlopera.com/")

public class GetListaCMFPorCampeonatoGanadoResponse {

    @XmlElement(name = "return")
    private com.wlopera.cliente.domain.Campeonato[] _return;

    public com.wlopera.cliente.domain.Campeonato[] getReturn() {
        return this._return;
    }

    public void setReturn(com.wlopera.cliente.domain.Campeonato[] new_return)  {
        this._return = new_return;
    }

}

