
package com.wlopera.cliente.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Sat Oct 27 10:24:12 COT 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "getListaCMFTodos", namespace = "http://cliente.wlopera.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getListaCMFTodos", namespace = "http://cliente.wlopera.com/")

public class GetListaCMFTodos {


}

